### ISSUE TITLE
early auto terminates 

### ISSUE THREAD

**Issue by ummmyey** [Fytex/Instagram-Giveaways-Winner#11]
it all goes to plan but when it writes the comment when posting it,it hits the emoji button and do nothing and after a few seconds it will shut it self down and when i run it with cmd it says early termination, 0 comments so far.. could you please say what's the problem...?i don't know anything about coding just wanted to hook this and use it could you please help me out?

**Comment by Jewpiter7** [comment]
Got the same problem today after latest windows update, the version 20H2..

**Comment by ummmyey** [comment]
still Looking For A Fix..

**Comment by yeaahboyy** [comment]
Yeah Can Please Somebody Help Fast I Have The Same Problem And Took A Look At The Script And Couldn't Understand What's The Problem i'm So In need Of This software Can somebody Take A Look At It

**Comment by Fytex** [comment]
@ummmyey @Jewpiter7 @yeaahboyy
Since this is a web-scrapping script it really depends on Instagram's front-end.
What happened was that they updated their front-end leading the script to new errors.
I solved the bugs. I'll leave this issue opened for a while in case you find a new related bug.
Appreciate your help :)

**Comment by yeaahboyy** [comment]
DAMN BRO YOU CAME JUST THE RIGHT TIME IT HELPED A LOT

**Comment by ummmyey** [comment]
Common Dude You're An Angel The Problem Got Fixed Ijest Neded Yhe Software Tonight Thanks For Fixing IT
