### ISSUE TITLE
bot i runnig ...

### ISSUE THREAD

**Issue by diasostis** [Fytex/Instagram-Giveaways-Winner#5]
bot running but stops after 14 comments...
the the browser says ...Coulnt post...
and this keeps going for ever....

**Comment by Fytex** [comment]
That is called rate-limit. What happens is that Instagram notices that you are spamming and rate-limits you. What I mean by this is that if you post too many comments in a short period of time Instagram will temporary block you from posting comments. 

Now you might think "Why just not wait until it's possible to post comments again". 

The answer to that is: Well they don't give us how much time left until we are able to post again. So to prevent this you have to raise the values ("Min", "Weight" and "Max") in `config.ini`. You shouldn't use the same value for those 3 in order to make the interval between comments a random number so instagram won't notice so easily that you are spamming. 

The number of comments you can post per hour/day depends on your account. You have to find those best values that fit better on your account. The more you use your account (commenting, liking, posting, etc.) the more comments you can post

**Comment by diasostis** [comment]
Yes i now but why can i make 120 comments with no time restriction at once on one post with my phone, and only 14 with the Instagram-Giveaways-Winner. ???

**Comment by Fytex** [comment]
Even raising those values ("MIN", "MAX", "WEIGHT")? You sure the rate limit wasn't because you have already posted many comments before using the bot?

**Comment by diasostis** [comment]
yes i did tried with other accounts as well .. but the same...
i thouht maybe the pc goes to hypernate ! but this was not the case...

**Comment by Fytex** [comment]
Hmm. Thats something that really requires searching because Instagram doesn't provide how their algorithm works.
I'm assuming that rate-limit was clean when you executed the bot and that the bot is doing the same thing step by step at almost the same interval or more per comment as you were doing manually. In that case the only thing I can think about is Instagram mobile allowing you to post more comments which kinda makes some sense.
